language: python
python:
- 3.10
- 3.9
- 3.8
install:
- pip install -U tox-travis
- pip install codecov
after_success:
- codecov
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: TheoDlmz
  password:
    secure: PNjjVUNxsajU2QU1cywP09QjJWyQnq+j4jXTW9COTk4fY019PYXiBEldfLL4bN0mfUpE5zSKPQlXG55NGyF7DRnQ1GabIAfAWFBsvYth5CYgz5HgW5K2mghBGlvdVsdA+uivLew4Bb08Jtv3BAHFS8/QZeCCj+5F87/kmthe1nDCmOsVRueGyt0vzVjLf0N86PbIn3+ISlanqVKxp8h2MXU6Ehmu4+HFhV417lUPJouiYt/be98Bfui+5DsSA0KLbFhR6q4MrnpEqcYQQKD2krQhjmPR8z0zIoh4CZWrwQ88E5KSFZ6nF87jZscQvDZSj0YaE8ghxpaUQbnOH1udZbxNySdjbA5g9dckt1b8jTjNvoq59Xmdbq7hFcbZeNd41lelmy+/bYT4r8Hpi/FWDGG3hLOoikRTDvr9PrEc5WXCa1mBs39XHY/FoZ1AMhIOZyVBlseKz0hfDgfii9tcf0CH7A6WohxxfL9AfuG4ktR75Iu23UlmmMScrEQwjeC0AQ49aj945uEI7G2sMfNl7mKPdfDM8Jqefmk0vKFAgwj58mIsKgA2QN8qZtzU51xQyNCzLVs6SfDpOL2M4fpFDxq+CO5GKK8oW6oVPfBtCI0v1jVSf5iRRyZfjyo1w01icXawpdS0SKpipDEVlVa0kNPWaHlhLrQNBP2e9t9E/oM=
  on:
    tags: true
    repo: TheoDlmz/embedded_voting
    python: 3.8
