from embeddings_from_ratings import EmbeddingsFromRatings
from embeddings_from_ratings_correlation import EmbeddingsFromRatingsCorrelation
from embeddings_from_ratings_identity import EmbeddingsFromRatingsIdentity
from embeddings_from_ratings_random import EmbeddingsFromRatingsRandom
from embeddings_from_ratings_self import EmbeddingsFromRatingsSelf
